<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Pierre Marquet and Jason">
    <title>Argonaute</title>
    <link rel="stylesheet" type="text/css" href="style.css" />
</head>

<body>
    <!-- Header section -->
    <header>
        <h1>
            <img src="https://www.wildcodeschool.com/assets/logo_main-e4f3f744c8e717f1b7df3858dce55a86c63d4766d5d9a7f454250145f097c2fe.png" alt="Wild Code School logo" />
            Les Argonautes
        </h1>
    </header>

    <!-- Main section -->
    <main>

        <!-- New member form -->
        <h2>Ajouter un(e) Argonaute</h2>
        <form action="index.php?addcrew" method="POST" class="new-member-form">
            <label for="name">Nom de l'Argonaute</label>
            <input id="name" name="name" type="text" placeholder="Charalampos" pattern="[A-Za-zÀ-ÿ]{1,50}" required="required" />
            <button type="submit">Envoyer</button>
        </form>

        <!-- Member list -->
        <h2>Membres de l'équipage</h2>
        <section class="member-list">
            <?php if (isset($list) && $list != null) : ?>
                <?php foreach ($list as $crewList) : ?>
                    <div class="member-item"><?= $crewList['name']; ?></div>
                <?php endforeach ?>
            <?php else : ?>
                <div>Il n'y a aucun équipage pour le moment</div>
            <?php endif ?>
        </section>

    </main>

    <footer>
        <p>Réalisé par Jason en Anthestérion de l'an 515 avant JC</p>
        <!-- Et Pierre Marquet en l'an 2020 après JC -->
    </footer>
</body>

</html>